name: Continuous Integration

on:
  push:
    branches: [ main, master, develop ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker image (test)
      uses: docker/build-push-action@v5
      with:
        context: .
        push: false
        target: production
        cache-from: type=gha
        cache-to: type=gha,mode=max

    - name: Test Docker build
      run: |
        docker build --target production -t tracks-test .
        echo "✓ Docker build successful"

    - name: Check for required files
      run: |
        test -f docker-compose.yml || (echo "❌ docker-compose.yml missing" && exit 1)
        test -f Dockerfile || (echo "❌ Dockerfile missing" && exit 1)
        test -f tracks_apptainer.def || (echo "❌ tracks_apptainer.def missing" && exit 1)
        test -f Makefile || (echo "❌ Makefile missing" && exit 1)
        echo "✓ All required files present"
